### ISSUE TITLE
does this library solve this problem?

### ISSUE THREAD

**Issue by the1mills** [mongodb-js/mongodb-language-model#10]
does this library solve this problem?
https://stackoverflow.com/questions/49332983/validate-a-mongodb-query-syntax-programmatically

**Comment by pzrq** [comment]
@the1mills What do you think?

**Comment by the1mills** [comment]
bump pls

**Comment by durran** [comment]
This library supports validating MongoDB queries on the client side as you're looking for, but it's unfortunately not complete at the moment (there are many operators that are not supported). In the next 2 months, we'll be deprecating this library in favour of a new parser, but it is still a bit away from production ready. But close. See: https://github.com/mongodb-js/bson-compilers
